# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=80)),
                ('service_image', models.ImageField(upload_to='services_images')),
                ('service_description', models.TextField()),
            ],
        ),
    ]
